
<?php

return [
    'ROLE_GESTORE' => 'ROLE_GESTORE', 
    'ROLE_ADMIN' => 'ROLE_ADMIN', 
    'ROLE_MASTER' => 'ROLE_MASTER',
    'ROLE_MODERATORE_ON'=> 'ROLE_MODERATORE_ON',
    'ROLE_MODERATORE_OFF'=> 'ROLE_MODERATORE_OFF',
    'ROLE_TUTOR' => 'TUTOR' 

];


?>